### ISSUE TITLE
Preguntas (cortas) sobre el Control 4

### ISSUE THREAD

**Issue by aaossa** [IIC2113/Syllabus-2022-1#23]
¡Hola!

La idea de esta _issue_ es que puedan dejar sus preguntas sobre los contenidos o aspectos formales del Control 4: ingeniería inversa, paradigmas de programación y ética en ingeniería de software. Si sus preguntas son largas, por favor hagan otra _issue_ y la responderemos a la brevedad. **La idea de este espacio es poder ayudarles a resolver dudas cortas**, rápidas de responder, para que puedan prepararse bien para el control. Sí o sí, responderé las dudas que lleguen **hasta el jueves 9 de junio a las 18:30** (a medida que llegan). ¡Mucho éxito preparando el Control 4!

**Comment by SebaHagedorn** [comment]
Hola! Qué tipo de preguntas se harán mañana? Preguntas mas conceptuales o aplicar los conceptos en un caso real o ficticio?

**Comment by aaossa** [comment]
Hola @SebaHagedorn , será un control principalmente conceptual (no hay código relacionado, por lo mismo será presencial) y también de aplicación de algunas de las ideas que vimos en clases. Te recomiendo ver las diapositivas de la Clase 7 y los casos referenciados en la Clase 8. ¡Éxito con tu preparación!

**Comment by SebaHagedorn** [comment]
Gracias por la respuesta!
